version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      DISPLAY: ":0.0"

    steps:
      - checkout
      - run: ./bin/build-test-snapshot.sh && ./bin/publish-snapshot-containers.sh CI
